### ISSUE TITLE
APP Server is not detected.

### ISSUE THREAD

**Issue by hendisantika** [sayadi/elastic-apm-spring-boot-integration#1]
Hi, nice sample.

I have some issue APP Server is not detected.

![image](https://user-images.githubusercontent.com/3713580/134100365-0479ecad-8e0d-4f0e-bfbc-9532bbf34e1f.png)

I have follow your repo & instruction. But nothing change.

Any suggestion?

Thanks

**Comment by sayadi** [comment]
Hey Hendi,

It's hard to tell what might be going wrong without more details.

Is the APM container running? Are there any errors in its logs?
Are the Spring applications able to connect to the APM server? Are there any logs there that would indicate that?

**Comment by hendisantika** [comment]
Hi @sayadi , I created the repo based on your repo. Maybe I You have time You can chech my repo https://github.com/hendisantika/spring-boot-elastic-apm-integration.

Thanks

**Comment by sayadi** [comment]
Got it.

In `properties`, the `elastic.apm.server-url` is set to `http://localhost:8080`.
In `docker-compose.yml`, the apm server listens on `8200`.
These two ports should be equal. I'd suggest changing it in properties to `8200`.

Hope this helps.

**Comment by hendisantika** [comment]
Ups. My mistake. It's working now. Thank You so much.

Your repo & article are very helpful to me.

**Comment by sayadi** [comment]
Awesome!
Glad you find the article and the repository helpful.
